version: "3.7"
services:

  proxy-https-to-http:
    build:
      context: .
      dockerfile: Dockerfile-proxy-https-http
    ports:
    - "10000:10000"

  service-http:
    image: mendhak/http-https-echo:23
    hostname: service-http
    volumes:
    - ./certs/front-proxy-crt.pem:/app/fullchain.pem
    - ./certs/front-proxy-key.pem:/app/privkey.pem
    environment:
    - HTTPS_PORT=0
    - HTTP_PORT=80